### PR TITLE
Add hot reloading feature

### PR DESCRIPTION
**Pull request by algomaster99**
I configured hot module replacement for this project.

#### Dependencies added
-  `webpack`: Used for module bundling. Everything under `src/` will be bundled as `build/build.js`.
-  `webpack-cli`: Used to run webpack commands in command line.
-  `webpack-node-externals`: To avoid bundling dependencies of express.
-  `ts-loader`: Enables webpack to transpile TypeScript code.
-  `nodemon`: Watches for changes in `build/build.js` and restarts the server accordingly.

### CODE REVIEW

**Comment by algomaster99** [comment]
I suggest testing the setup till now because the next step will be adding models which is the actual start to the project.

**Comment by siddhant1** [comment]
Looks good ! I have also made a pr to refactor some parts of the setup process ! Can you also see that and include in this one , I will close that pr after that!

**Comment by domoritz** [comment]
I don't think we need a bundler at all, do we?

**Comment by algomaster99** [comment]
@domoritz only one package i.e. webpack will transpile and provide us with hmr feature. It is beneficial to use it. The build is also optimized in size.

**Comment by siddhant1** [comment]
In my opinion our backend it very small , I think a setup of js+express+nodemon will be perfect for this one

**Comment by algomaster99** [comment]
@siddhant1 using webpack makes writing config files easier too. One config does all the work. Otherwise there will be a separate config for transpiling and watching files.

**Comment by domoritz** [comment]
Webpack is made for packaging web code for the web. I have never seen it being used for servers. Our code is so simple so isn't `tsc -w` and a simple server reloader enough?

**Comment by algomaster99** [comment]
@domoritz okay I will try writing configurations without webpack too.

**Comment by algomaster99** [comment]
@siddhant1 @domoritz Is it fine now?

**Comment by siddhant1** [comment]
Can you update the tsconfig , as I did in another pr , there are still some changes required

**Comment by algomaster99** [comment]
@siddhant1 we won't need them since we are no longer transpiling TypeScript. We are running it in a `ts-node` environment.

**Comment by siddhant1** [comment]
We need to remove linting from node_modules and remove the "dom" , I recommend using the tsconfig that the Microsoft starter and provides

**Comment by algomaster99** [comment]
@siddhant1 let's have minimalistic configurations for the project. We can add more configuration should there be a need.
And yes, for not linting node_modules, I'll add the conf.

**Comment by algomaster99** [comment]
@siddhant1 One more thing won't it be better to specify ignoring `node_modules` in `.eslintignore`?
And what does `dom` do?

**Pull request merged**
